### PR TITLE
Add IDEActivityLogActionMessage support

### PR DESCRIPTION
**Pull request by mollyIV**
Closes https://github.com/MobileNativeFoundation/XCLogParser/issues/187. 

Add IDEActivityLogActionMessage support.

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
@mollyIV Sorry for the delay! Do you mind fixing the DCO check and possibly add a few tests? There's a [test class](https://github.com/MobileNativeFoundation/XCLogParser/blob/master/Tests/XCLogParserTests/ActivityParserTests.swift) for this specific logic which we can use.

**Comment by mollyIV** [comment]
Hey @BalestraPatrick 👋 

No worries 😊 I fixed DCO check and added a unit test. Thanks for pointing to a test class. Let me know if there's anything else I can do, thanks!

**Comment by BalestraPatrick** [comment]
Looks good to me! One minor linter failure which you can disable with `// swiftlint:disable file_length`.

**Review by BalestraPatrick — APPROVED** [review]

**Comment by danielPeloton** [comment]
Thanks for pushing this through!

Is there a plan to get this into a new release?

**Pull request merged**
