### PR TITLE
Skip parsing of section attachments for logs with version less than 11

### LINKED ISSUE #209: parse xcode14.3 xcactivitylog error
The latest version can parse the logs of Xcode 15.3 without any issues, but fails to parse the logs from the older Xcode 14.3. The error message is: "Error: Error parsing the log: Unexpected token parsing array of IDEActivityLogSectionAttachment: [type: classNameRef, className: 'IDEActivityLogSection']."

### LINKED ISSUE #211: Unexpected token parsing array of IDEActivityLogSectionAttachment
Found error with xcode 15.1 

 _Unexpected token parsing array of IDEActivityLogSectionAttachment_

how to fix this issue please.

### PR DESCRIPTION
**Pull request by HeEAaD**
Fixes #211
Fixes #209 

This resolves the regression introduced by #204 that parsing of older logs (pre Xcode 15.3) raises the error `Unexpected token parsing array of IDEActivityLogSectionAttachment`.

Parse the `IDEActivityLogSectionAttachments` list only for activity logs with version 11 or above because this list is missing in version 10 logs.

Thanks @yohunl for the inspiration for the fix. https://github.com/MobileNativeFoundation/XCLogParser/issues/209#issuecomment-2055828404

### CODE REVIEW

**Comment by MasterWatcher** [comment]
@polac24 @ecamacho @aleksandergrzyb @CognitiveDisson Hi guys! Could you please review this pull request? It's impossible to use XCLogParser on Xcode before 15.3 without it.

**Review by aleksandergrzyb — APPROVED** [review]

**Comment by giovaninb** [comment]
Up! I'm waiting for this review

**Comment by rcek2** [comment]
Up! @polac24 @ecamacho @CognitiveDisson please 🙏

**Comment by aleksandergrzyb** [comment]
@HeEAaD not sure why, but the checks fail with `couldn't find remote ref refs/pull/213/merge`. In #218 I updated the checkout action version, could you rebase?

**Comment by HeEAaD** [comment]
@aleksandergrzyb @kalebhermes I've just rebased. Unit tests succeed locally.

Please approve the workflow run.

**Review by aleksandergrzyb — APPROVED** [review]

**Comment by aleksandergrzyb** [comment]
We also had to upgrade macOS version, could you rebase on #222?

**Comment by HeEAaD** [comment]
> We also had to upgrade macOS version, could you rebase on #222?

done

**Pull request merged**
